# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - pinecone
    build: ./
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-pinecone}
      PINECONE_HOST: ${PINECONE_HOST:-pinecone}
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]

  redis:
    image: "pinecone/pinecone-stack-server:latest"
